import type { PermisoModule } from "@/hooks/usePermisos";

/** Maps route paths to permission module keys */
export const routeToModule: Record<string, PermisoModule> = {
  "/dashboard": "dashboard",
  "/cobranza": "cobranza",
  "/mi-cobranza": "mi_cobranza",
  "/prestamos": "prestamos",
  "/pagos": "pagos",
  "/promesas": "promesas",
  "/solicitudes": "solicitudes",
  "/clientes": "clientes",
  "/crm": "crm",
  "/scoring": "scoring",
  "/mapa-gps": "mapa_gps",
  "/cajas": "cajas",
  "/gastos": "gastos",
  "/comisiones": "comisiones",
  "/liquidar-ruta": "liquidar_ruta",
  "/reportes": "reportes",
  "/cobradores": "cobradores",
  "/rutas": "rutas",
  "/usuarios": "usuarios",
  "/empresas": "empresas",
  "/configuracion": "configuracion",
  "/catalogos": "catalogos",
  "/whatsapp": "whatsapp",
  "/permisos": "permisos",
  "/alertas": "dashboard",
  "/renovacion": "prestamos",
  "/rentabilidad": "reportes",
  "/auditoria": "permisos",
  "/productividad": "reportes",
  "/mi-suscripcion": "configuracion",
};
