project_id = "oewuzgugsjqtznmgnfhp"

[functions.stripe-connect-onboard]
verify_jwt = false

[functions.stripe-connect-status]
verify_jwt = false

[functions.stripe-create-payment-link]
verify_jwt = false

[functions.stripe-charge-cuota]
verify_jwt = false

[functions.stripe-sync-payment-method]
verify_jwt = false

[functions.stripe-auto-charge]
verify_jwt = false

[functions.whatsapp-sender]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.admin-create-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false